### ISSUE TITLE
Plugin has stopped working, since upgrading to Crestron OS4

### ISSUE THREAD

**Issue by DiggyS** [evgolsh/homebridge-crestron-home#12]
**Describe The Bug:**
Plugin is not working, seems to be after upgrading to Crestron Home OS4.

**To Reproduce:**
Is constant

**Expected behavior:**
Would expect to control lights and shades from Apple HomeKit, they were working, none are working now.

**Logs:**
Login error:  Request failed with status code 500
[3/24/2024, 8:34:57 PM] [Crestron Home Platform] error getting devices:  TypeError: Cannot read properties of undefined (reading 'get')
    at CrestronClient.getDevices (/volume1/homebridge/node_modules/homebridge-crestron-home/src/crestronClient.ts:75:26)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CrestronHomePlatform.updateDevices (/volume1/homebridge/node_modules/homebridge-crestron-home/src/platform.ts:168:21)

**Plugin Config:**
{
    "name": "Crestron Home Platform",
    "crestronHost": "192.168.3.6",
    "token": "xxxxxxxxxxxx",
    "enabledTypes": [
        "Switch",
        "Dimmer",
        "Shade"
    ],
    "updateInterval": 10,
    "_bridge": {
        "username": "0E:8E:12:9B:ED:12",
        "port": 56820
    },
    "platform": "CrestronHomePlatform"
}

**Screenshots:**

**Environment:**

* **Plugin Version**: v1.1.8
* **Homebridge Version**: 1.7.0
* **Node.js Version**: v18.18.2
* **NPM Version**:
* **Operating System**: Synology App

**Comment by evgolsh** [comment]
Try to reboot the controller, it usually fixes the problem. Regenerate token if not.

**Comment by DiggyS** [comment]
Sorry you are 100% right, I should have tried that. Had recently reboot becuase of update, so did not try that again.
The token regenerate i had tried, that did not make a difference, was other reboot that sorted it.
Thank you.
