### ISSUE TITLE
Request accessories not be included in favorites by default

### ISSUE THREAD

**Issue by tweihs** [evgolsh/homebridge-crestron-home#2]
**Is your feature request related to a problem? Please describe:**

When plugin is installed, accessories are added to favorites. User then has to remove all accessories from and reorganized their favorites to clean this up.

**Describe the solution you'd like:**

Accessories are not automatically added to favorites when plugin is installed.

**Describe alternatives you've considered:**

None

**Additional context:**

None

**Comment by evgolsh** [comment]
Hi, I think this is the Apple HomeKit behavior and not related to Homebridge
