### ISSUE TITLE
More than 149 devices on Switches Alone

### ISSUE THREAD

**Issue by HypocritePro** [evgolsh/homebridge-crestron-home#4]
One this one setup for our new office, we have well over 149 legs (switches and or dimmers) and the issue is the warning that 
plugin will continue to crash... it imports up to 149 of the switches alone (no dimmers, shades, or scenes on the child bridge, or installed at all in this instance) and then truncates the rest with the warning.

Is there any further way to segregate the switches alone into 2 parts (child bridges) as to overcome this issue/limitation?

**Log**

5/2/2023, 6:49:09 PMCrestron Home HOOBs starting
5/2/2023, 6:49:20 PMCrestron Home HOOBsLoaded plugin 'homebridge-crestron-home'
5/2/2023, 6:49:20 PMCrestron Home HOOBsLoading 1 platforms...
5/2/2023, 6:49:20 PMCrestron Home HOOBsCrestron Home HOOBsLoading accessory from cache: 1.1 - Main Washroom Main Washroom Blind - Blackout
5/2/2023, 6:49:20 PMCrestron Home HOOBsCrestron Home HOOBsLoading accessory from cache: 1.1 - Main Washroom Main Washroom Blind - Shade
5/2/2023, 6:49:20 PMCrestron Home HOOBsBridge is running on port ********.
5/2/2023, 6:49:21 PMCrestron Home HOOBsCrestron Home HOOBsSuccsessfully authinticated, working with version:  2.000.0003
5/2/2023, 6:49:21 PMCrestron Home HOOBsCrestron Home HOOBsWARNINGReturning more than 149 devices, Bridge may crash -  257
5/2/2023, 6:49:21 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 2.2 - ********
5/2/2023, 6:49:21 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 2.1 - ********
5/2/2023, 6:49:21 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 2.2 - ********
5/2/2023, 6:49:21 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 2.2 - ********
5/2/2023, 6:49:21 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 2.1 - ********
5/2/2023, 6:49:21 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 2.1 - ********
5/2/2023, 6:49:21 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 1.4 - ********
5/2/2023, 6:49:21 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 1.2 - ********
5/2/2023, 6:49:22 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 1.0 - ********
5/2/2023, 6:49:22 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 1.0 - ********
5/2/2023, 6:49:22 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 1.0 - ********
5/2/2023, 6:49:22 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 1.0 - ********
5/2/2023, 6:49:22 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 1.5 - ********
5/2/2023, 6:49:22 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 1.4 - ********
5/2/2023, 6:49:22 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 1.4 - ********
5/2/2023, 6:49:22 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 3.3 - ********
5/2/2023, 6:49:22 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 3.1 - ********
5/2/2023, 6:49:22 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 3.1 - ********
5/2/2023, 6:49:22 PMCrestron Home HOOBsCrestron Home HOOBsAdding new accessory: 3.2 - ********
5/2/2023, 6:49:22 PMCrestron Home HOOBsCrestron Home HOOBsRestoring existing accessory from cache: 1.1 - ********
5/2/2023, 6:49:22 PMCrestron Home HOOBsCrestron Home HOOBsRestoring existing accessory from cache: 1.1 - ********
5/2/2023, 6:49:50 PMCrestron Home HOOBsCrestron Home HOOBsUpdating Devices state
5/2/2023, 6:49:50 PMCrestron Home HOOBsCrestron Home HOOBsWARNINGReturning more than 149 devices, Bridge may crash -  257
5/2/2023, 6:50:20 PMCrestron Home HOOBsCrestron Home HOOBsUpdating Devices state
5/2/2023, 6:50:20 PMCrestron Home HOOBsCrestron Home HOOBsWARNINGReturning more than 149 devices, Bridge may crash -  257

**Plugin Config:**

{
    "platform": "CrestronHomePlatform",
    "name": "Crestron Home HOOBs",
    "loginInterval": 4,
    "crestronHost": "192.168.1.***",
    "token": "********",
    "enabledTypes": [
        "Switch"
    ]
}

* **Plugin Version**: 1.1.5
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 16.20.0
* **Operating System**: Hoobs 4.3.0

**Comment by evgolsh** [comment]
In the current implementation there is no way to split lights if you have more than 149 accessories of the same type in the same bridge (this is Apple HomeKit limitation). 

How would you want to split it? By room?
