### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by gordonxman** [evgolsh/homebridge-crestron-home#8]
Would it be possible to have a toggle in settings to turn off logging? 

Whilst " [Crestron] Updating Devices state" is handy early on, its hard to find other errors over time. 

Appreciate the work here and the pluggin is excellent.

Thanks.

**Comment by evgolsh** [comment]
Fixed in 1.1.8

**Comment by gordonxman** [comment]
Updated to 1.1.8. Did you add a logging setting that I have missed? Nothing appears in the Config window.

Many thanks.

**Comment by evgolsh** [comment]
I just fixed wrong warning message. You can set Homebridge logging level to `error` only, if `info` bothers you too much.
